version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=sqlite:///instance/chatbot.db
      - SECRET_KEY=${SECRET_KEY}
      - SNOW_INSTANCE=${SNOW_INSTANCE}
      - SNOW_USERNAME=${SNOW_USERNAME}
      - SNOW_PASSWORD=${SNOW_PASSWORD}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web

volumes:
  redis_data:
  static_volume: 